baseURL = "http://localhost:1313/"
title = "szakky's Blog"
theme = "PaperMod"

languageCode = "ja-jp"

[params.homeInfoParams]
Title = "Welcome!"
Content = """
This blog documents my hands-on experience logs
"""

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'